name: sam_uiz
description: "A customizable UI components library (Button, Card, Input Box)."
version: 0.0.2
homepage: https://github.com/dizzpy/sam_uiz

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

contact: dizzzpy@gmail.com
